nodeLinker: node-modules

npmRegistries:
  "https://npm.pkg.github.com":
    npmAlwaysAuth: true

npmScopes:
  golemfoundation:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"
