[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
exclude = ["script/**/*"]
evm_version = "prague"
optimizer = true
# Runs changed from 10M to 25k to fit code in EVM
optimizer_runs = 200
via_ir = false
solc = "0.8.30"
verbosity = 3
ast = true
fs_permissions = [
    { access = "read-write", path = "./cache/test-artifacts/" },
    { access = "read", path = "./out/" },
    { access = "read-write", path = "./ci/" }
]
build_info = true
extra_output = ["storageLayout"]
seed = "0xDEADC0DE"
fuzz = { runs = 256, max_test_rejects = 65536 }
deny_warnings = true

[profile.ci]
fuzz = { runs = 256, max_test_rejects = 65536 }

[profile.local]
fuzz = { runs = 50 }
invariant = { runs = 10 }
# Speed up compilation and tests during development.
optimizer = true

[profile.kprove]
src = 'src'
out = 'out'
test = 'proof/kontrol'
ast = true

[rpc_endpoints]
mainnet = "${TEST_RPC_URL}"

[soldeer]
#remappings_regenerate = true
remappings_version = false

[dependencies]
forge-std = ">=1.9.7"
solady = { version = "0.1.21", git = "https://github.com/vectorized/solady", tag = "v0.1.21" }
abdk-libraries-solidity = { version = "3.2", git = "https://github.com/abdk-consulting/abdk-libraries-solidity", tag = "v3.2" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
