[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000_000
solc = "0.8.25"
verbosity = 3
viaIR = true
remappings = [
    "@solady=lib/solady/src", # octant solady path
    "solady=lib/solady", # deps solady path
    "@uniswap/v3-periphery/contracts=lib/uniswap-v3-periphery-0.8/contracts",
    "@uniswap/v3-core/contracts=lib/uniswap-v3-core-0.8/contracts"
]

[profile.ci]
fuzz = { runs = 5000 }
invariant = { runs = 1000 }
verbosity = 4

[profile.local]
  fuzz = { runs = 50 }
  invariant = { runs = 10 }
  # Speed up compilation and tests during development.
  optimizer = true

[rpc_endpoints]
mainnet = "${ETHEREUM_NODE_MAINNET}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
