[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000_000
solc = "0.8.28"
verbosity = 3
ast = true
fs_permissions = [{ access = "read-write", path = "./cache/test-artifacts/" },{ access = "read", path = "./out/"}]
build_info = true
extra_output = ["storageLayout"]
[profile.ci]
invariant = 256
verbosity = 4

[profile.default.fuzz]
runs = 1000
seed = "0xDEADC0DE"

[profile.pr.fuzz]
runs = 256

[profile.ci.fuzz]
runs = 256

[rpc_endpoints]
mainnet = "${ETHEREUM_NODE_MAINNET}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
