[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "shanghai"
optimizer = true
optimizer_runs = 10_000_000
solc = "0.8.23"
verbosity = 3
remappings = [
    "@solady=lib/solady/src/", # octant solady path
    "solady=lib/solady/src/",  # deps solady path
    "@diva/contracts=lib/smartcontract/contracts/",
    "@uniswap/v3-periphery/contracts=lib/uniswap-v3-periphery-0.8/contracts/",
    "@uniswap/v3-core/contracts=lib/uniswap-v3-core-0.8/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@splits/splits-pass-through-wallet=lib/splits-pass-through-wallet/src/"
]

[profile.ci]
fuzz = { runs = 5000 }
invariant = { runs = 1000 }
verbosity = 4

[profile.local]
  fuzz = { runs = 50 }
  invariant = { runs = 10 }
  # Speed up compilation and tests during development.
  optimizer = false

[rpc_endpoints]
mainnet = "${ETHEREUM_NODE_MAINNET}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
