[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "shanghai"
optimizer = true
optimizer_runs = 10_000_000
solc = "0.8.23"
verbosity = 3
remappings = [
    "@solady=lib/solady/src", # octant solady path
    "solady=lib/solady", # deps solady path
    "@diva/contracts=lib/smartcontract/contracts"
]

[profile.ci]
fuzz = { runs = 5000 }
invariant = { runs = 1000 }
verbosity = 4

[profile.local]
  fuzz = { runs = 50 }
  invariant = { runs = 10 }
  # Speed up compilation and tests during development.
  optimizer = false

[rpc_endpoints]
mainnet = "${ETHEREUM_NODE_MAINNET}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
