[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
evm_version = "cancun"
optimizer = true
# Runs changed from 10M to 25k to fit code in EVM
optimizer_runs = 1
solc = "0.8.30"
verbosity = 3
ast = true
fs_permissions = [
    { access = "read-write", path = "./cache/test-artifacts/" },
    { access = "read", path = "./out/" },
    { access = "read-write", path = "./ci/" }
]
build_info = true
extra_output = ["storageLayout"]
seed = "0xDEADC0DE"
fuzz = { runs = 256, max_test_rejects = 65536 }
deny_warnings = true

[profile.ci]
fuzz = { runs = 256, max_test_rejects = 65536 }

[profile.local]
fuzz = { runs = 50 }
invariant = { runs = 10 }
# Speed up compilation and tests during development.
optimizer = true

[profile.kprove]
src = 'src'
out = 'out'
test = 'proof/kontrol'
ast = true

[rpc_endpoints]
mainnet = "${TEST_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
