name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  FOUNDRY_PROFILE: ci

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 16.x

    name: Octant V2 Core Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x.x

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run npm install
        run: "npm i"

      - name: Run Forge build
        run: "forge build"

  test:
    strategy:
      fail-fast: true

    name: Octant V2 Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x.x

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1

      - name: Run npm install
        run: "npm i"

      - name: Run tests
        env:
          ETHEREUM_NODE_MAINNET: ${{ secrets.ETHEREUM_NODE_MAINNET }}
        run: forge test -v

  coverage:
    strategy:
      fail-fast: true

    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x.x

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run npm install
        run: "npm i"

      - name: Run coverage
        run: forge coverage --report summary --report lcov
