name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  FOUNDRY_PROFILE: ci

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 16.x

    name: Octant V2 Core Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x.x

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run npm install
        run: "npm i"

      - name: Run Forge build
        run: "forge build"

  test:
    strategy:
      fail-fast: true

    name: Octant V2 Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x.x

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1

      - name: Run npm install
        run: "npm i"

      - name: Run tests
        env:
          # this key will get rotated
          TEST_RPC_URL: "https://eth-mainnet.alchemyapi.io/v2/Mb7EMfWKg8dC7_BUbzjRi-G25WUTnR5E"
          TEST_SAFE_SINGLETON: "0x41675C099F32341bf84BFc5382aF534df5C7461a"
          TEST_SAFE_PROXY_FACTORY: "0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67"
          TEST_RPC_URL_POLYGON: "https://polygon-rpc.com"
          TEST_SAFE_SINGLETON_POLYGON: "0x41675C099F32341bf84BFc5382aF534df5C7461a"
          TEST_SAFE_PROXY_FACTORY_POLYGON: "0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67"
        run: forge test -v

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x.x

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1

      - name: Run npm install
        run: "npm i"

      - name: Run Slither
        uses: crytic/slither-action@v0.4.0
        with:
          target: "src/"
